# Generated by Django 3.1.2 on 2020-11-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aff_bank', to='shop.affiliate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='KYC',
            field=models.ImageField(blank=True, null=True, upload_to='KYC'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Nepal', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(default='Kathmandu', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Vendor_Profile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ward_no',
            field=models.IntegerField(null=True),
        ),
    ]
