# Generated by Django 3.1.2 on 2020-11-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='created_by',
        ),
        migrations.AddField(
            model_name='product',
            name='commision',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
