# Generated by Django 3.1.2 on 2020-11-19 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201113_2107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_auto_20201119_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'sub_category',
                'verbose_name_plural': 'sub_categories',
                'ordering': ('brand_name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='SKU',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allovernepal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cashpayment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.CharField(choices=[('HotSale', 'Hot Sale'), ('FlashSale', 'Flash Sale'), ('ExclusiveSale', 'Exclusive Sale'), ('Normal', 'Normal')], default='Normal', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='shippingarea',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product', to='shop.vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortime', models.CharField(choices=[('6', 'For 6 Month'), ('1', 'For One Year'), ('2', 'For Two Year'), ('3', 'For Three Year'), ('4', 'For 4 Years'), ('5', 'For 5 Years'), ('10', 'For 10 Years'), ('15', 'For 15 Years'), ('20', 'For 20 Years')], max_length=200)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_product', to='staff.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='staff.brand'),
        ),
    ]
